spring:
  application:
    name: bff-clean-arch-insurance-customer

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

external:
  customer-api:
    base-url: http://localhost:8081

  policy-api:
    base-url: http://localhost:8081

  vehicle-api:
    base-url: http://localhost:8081